apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

helmCharts:
    - name: gateway
      repo: https://istio-release.storage.googleapis.com/charts
      version: 1.23.0-rc.1
      releaseName: istio-gateway
      namespace: istio-ingress

resources:
  - namespace.yaml

generatorOptions:
    disableNameSuffixHash: true



