apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonAnnotations:
  annotations:
    #argocd.argoproj.io/sync-wave: "-5"

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    version: "21.0.3"
    releaseName: argocd-redis
    namespace: argocd
    valuesFile: values.yaml

resources:
  - secrets/argocd-redis-credentials.yaml


