apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "58.5.3"
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml

# resources:
#   - secrets/argocd-redis-credentials.yaml



