apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    includeCRDs: true
    repo: https://prometheus-community.github.io/helm-charts
    version: "61.3.*"
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml




