---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-serving-operator-aggregated-stable
  labels:
    app.kubernetes.io/version: "1.14.5"
    app.kubernetes.io/name: knative-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-serving-operator-aggregated-stable
subjects:
  - kind: ServiceAccount
    name: knative-operator
    namespace: knative-operator

