apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

resources:
  - gc.yaml
  - domain.yaml
  - logging.yaml
  - network.yaml
  - tracing.yaml
  - defaults.yaml
  - features.yaml
  - autoscaler.yaml
  - deployment.yaml
  - cert-manager.yaml
  - observability.yaml
  - leader-election.yaml

generatorOptions:
  disableNameSuffixHash: true







