apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

resources:
  - 0-prometheus-rules.yaml
  #- 1-additional-scrape-configs.yaml
  - 2-federated-monitor.yaml

generatorOptions:
    disableNameSuffixHash: true



