apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: harbor-admin-password  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: harbor-admin-password
