# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: harbor-db-secret
# spec:
#   refreshInterval: 1h           # rate SecretManager pulls GCPSM
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: gcpsm                # name of the SecretStore (or kind specified)
#   target:
#     name: harbor-db-secret  # name of the k8s Secret to be created
#     creationPolicy: Owner
#   dataFrom:
#   - extract:
#       key: harbor-db-secret
# ---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-db-secret
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: harbor-db-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
  - secretKey: username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: harbor-db-secret
      property: username
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: harbor-db-secret
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-db-secret-adjusted
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: harbor-db-secret-adjusted  # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
  - secretKey: password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: harbor-db-secret
      property: password
  # dataFrom:
  # - extract:
  #     key: harbor-db-secret
  #   rewrite:
  #   - regexp:
  #       source: "(.*)"
  #       target: "password"



