apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-workflows-sso
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: argo-workflows-sso  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: argo-workflows-sso


