apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-workflow-webhook-clients
  labels:
    app.kubernetes.io/name: argo-workflow-webhook-clients
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: argo-workflow-webhook-clients   # name of the k8s Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      #type: kubernetes.io/dockerconfigjson
      data:
        github: |
          {{ .github }}
  data:
  - secretKey: github
    remoteRef:
      key: argo-workflow-webhook-clients

