apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-admin
  annotations:
    workflows.argoproj.io/rbac-rule: "'argocd-admin' in groups "
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-admin.service-account-token
  annotations:
    kubernetes.io/service-account.name: argo-admin
type: kubernetes.io/service-account-token

