apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
  labels:
    cert-manager.io/next-private-key: 'true'
    controller.cert-manager.io/fao: 'true'
spec:
  dnsNames:
    - external-secrets-webhook.external-secrets.svc.cluster.local
    - external-secrets-webhook.external-secrets.svc
  secretName: external-secrets-webhook
  issuerRef:
    name: selfsigned-ca-issuer
    kind: ClusterIssuer

