apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

helmCharts:
    - name: cert-manager-csi-driver
      repo: https://charts.jetstack.io
      version: v0.11.0
      releaseName: cert-manager-csi
      namespace: cert-manager
      valuesFile: values.yaml
      includeCRDs: true

generatorOptions:
    disableNameSuffixHash: true
