apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

commonAnnotations:
    reloader.stakater.com/auto: "true"

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: "0.22.0"
    releaseName: cnpg
    namespace: cnpg-system
    valuesFile: values.yaml

# generatorOptions:
#   disableNameSuffixHash: true

# resources:
#   - resources
#   - secrets

# patches:
#   - path: patches/metrics-server-extension.yaml

