---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: honker-cloud
  namespace: default
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
  secretName: honker-cloud-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - s3.honker.cloud
    - '*.s3.honker.cloud'
