---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    app.kubernetes.io/component: router
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/name: metrics-server
  ports:
    - name: https
      port: 10250
      protocol: TCP
      targetPort: https

