apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: trusted-bundle
  namespace: cert-manager
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: "ca-root"
      key: "tls.crt"
  target:
    configMap:
      key: "trusted-bundle.pem"
