---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: harbor-transport
  namespace: harbor
spec:
  serverName: container.health
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-ingress-route
  namespace: harbor
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`registry.container.health`)
      kind: Rule
      priority: 10
      services:
        - name: harbor
          port: 443
          scheme: https
          serversTransport: harbor-transport
      middlewares:
        - name: rate-limit
          namespace: traefik
        - name: https-redirectscheme
          namespace: traefik
        - name: default-headers
          namespace: traefik
        - name: compress
          namespace: traefik
  tls:
    secretName: container-health-tls





