apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-harbor
  namespace: harbor
spec:
  instances: 3
  bootstrap:
    initdb:
      database: harbor_core
      owner: harbor_user
      dataChecksums: true
      encoding: 'UTF8'
      secret:
        name: harbor-db-secret
  enableSuperuserAccess: true
  superuserSecret:
    name: harbor-super-db-secret
  storage:
    size: 20Gi
  walStorage:
    size: 5Gi

