apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-workflows
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/null0xeth/argo-cd.git
    path: charts/argo/argocd-workflows
    targetRevision: HEAD
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true

