apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-kustomize-components
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  source:
    path: kustomize/argocd-extensions/metrics/
    repoURL: https://github.com/null0xeth/argo-cd.git
    targetRevision: main
    # kustomize:
    #   components:
    #     - components
  syncPolicy:
    automated:
      selfHeal: true

  # This!

