apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ever-gauzy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  source:
    path: charts/ever-gauzy
    repoURL: https://github.com/null0xeth/argo-cd.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true



