apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  source:
    path: charts/kube-prometheus-stack
    repoURL: https://github.com/null0xeth/argo-cd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - validate=false
      - PrunePropogationPolicy=foreground
      - PruneLast=true
      - CreateNamespace=true



