apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kewb-prometheus
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  source:
    path: charts/kube-prometheus-stack
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true



