apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  additional_display_details:
    - title: "API Documentation"
      annotation: "kiali.io/api-spec"
      icon_annotation: "kiali.io/api-type"
  istio_namespace: ""

  version: "default"

  auth:
    strategy: "anonymous"

  clustering:
    autodetect_secrets:
      enabled: true
      label: "kiali.io/multiCluster=true"

  # default: custom_dashboards is an empty list
  custom_dashboards:
    - name: "envoy"

  deployment:
    # default: accessible_namespaces is undefined
    accessible_namespaces: null
    cluster_wide_access: true

    hpa:
      api_version: "autoscaling/v2"
      # default: spec is empty
      spec:
        maxReplicas: 5
        minReplicas: 1
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50

    image_pull_policy: "Always"
    # default: image_pull_secrets is an empty list
    image_pull_secrets: []
    instance_name: "kiali"

    logger:
      log_level: "info"
      log_format: "text"
      sampler_rate: "1"
      time_field_format: "2006-01-02T15:04:05Z07:00"

    namespace: "istio-system"

    pod_labels:
      sidecar.istio.io/inject: "false"
    replicas: 1

    service_type: "ClusterIP"
    view_only_mode: false

  external_services:
    custom_dashboards:
      enabled: true
    grafana:
      enabled: false
      #in_cluster_url: 'http://grafana.grafana:3000/'
    prometheus:
      url: http://prometheus-operated.istio-system:9090
    istio:
      component_status:
        components:
        - app_label: "istiod"
          is_core: true
          is_proxy: false
        - app_label: "istio-ingressgateway"
          is_core: true
          is_proxy: true
          # default: namespace is undefined
          namespace: istio-ingress
        - app_label: "istio-egressgateway"
          is_core: false
          is_proxy: true
          # default: namespace is undefined
          namespace: istio-system
        enabled: true
      config_map_name: "istio"
      envoy_admin_local_port: 15000
      gateway_api_classes: []
      istio_api_enabled: true
      # default: istio_canary_revision is undefined
      # istio_canary_revision:
      #   current: "1-9-9"
      #   upgrade: "1-10-2"
      istio_identity_domain: "svc.cluster.local"
      istio_injection_annotation: "sidecar.istio.io/inject"
      istio_sidecar_annotation: "sidecar.istio.io/status"
      istio_sidecar_injector_config_map_name: "istio-sidecar-injector"
      istiod_deployment_name: "istiod"
      istiod_pod_monitoring_port: 15014
      root_namespace: "istio-system"

    tracing:
      enabled: false

  identity:
    cert_file: ""
    private_key_file: ""

  istio_labels:
    app_label_name: "app"
    injection_label_name: "istio-injection"
    injection_label_rev: "istio.io/rev"
    version_label_name: "version"

  kiali_feature_flags:
    certificates_information_indicators:
      enabled: true
      secrets:
      - "cacerts"
      - "istio-ca-secret"
    disabled_features: []
    istio_annotation_action: true
    istio_injection_action: true
    istio_upgrade_action: false
    ui_defaults:
      graph:
        find_options:
        - description: "Find: slow edges (> 1s)"
          expression: "rt > 1000"
        - description: "Find: unhealthy nodes"
          expression: "! healthy"
        - description: "Find: unknown nodes"
          expression: "name = unknown"
        hide_options:
        - description: "Hide: healthy nodes"
          expression: "healthy"
        - description: "Hide: unknown nodes"
          expression: "name = unknown"
        traffic:
          grpc: "requests"
          http: "requests"
          tcp: "sent"
      i18n:
        language: "en"
        show_selector: false
      list:
        include_health: true
        include_istio_resources: true
        include_validations: true
        show_include_toggles: false
      metrics_per_refresh: "1m"
      # default: metrics_inbound is undefined
      metrics_inbound:
        aggregations:
        - display_name: "Istio Network"
          label: "topology_istio_io_network"
        - display_name: "Istio Revision"
          label: "istio_io_rev"
      # default: metrics_outbound is undefined
      metrics_outbound:
        aggregations:
        - display_name: "Istio Network"
          label: "topology_istio_io_network"
        - display_name: "Istio Revision"
          label: "istio_io_rev"
      # default: namespaces is an empty list
      namespaces: []
      refresh_interval: "1m"
    validations:
      ignore: ["KIA1301"]
      skip_wildcard_gateway_hosts: false

  kubernetes_config:
    burst: 200
    cache_duration: 300
    cache_token_namespace_duration: 10
    excluded_workloads:
    - "CronJob"
    - "DeploymentConfig"
    - "Job"
    - "ReplicationController"
    qps: 175

  login_token:
    expiration_seconds: 86400
    signing_key: ""

  server:
    address: ""
    gzip_enabled: true
    observability:
      metrics:
        enabled: true
        port: 9090
      tracing:
         enabled: false
    port: 20001
    profiler:
      enabled: true
    web_root: "/kiali"

