apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

resources:
  #- operator/subscription.yaml
  - kiali_instance.yaml

generatorOptions:
    disableNameSuffixHash: true




