---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-webhook-server-cert
  namespace: elastic-system
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
  secretName: elastic-webhook-server-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "elastic-webhook-server.elastic-system.svc"

