---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-admin
  annotations:
    workflows.argoproj.io/rbac-rule: "'argocd-admin' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-only
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"

