apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    includeCRDs: true
    repo: https://traefik.github.io/charts
    version: 33.0.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yml

generatorOptions:
  disableNameSuffixHash: true
