apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_cd_kustomize_schema.json

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: "7.1.3"
    #releaseName: argocd
    namespace: argocd
    apiVersions:
      - monitoring.coreos.com/v1
    valuesFile: values.yaml

resources:
  - resources
  - secrets

patches:
- path: patches/kustomize-helm.yaml
- path: patches/metrics-server-extension.yaml
