# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: istio-system
spec:
  strategy: production
  query:
    options:
      log-level: info
      query:
        base-path: /jaeger
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 500m
        memory: 516Mi
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 3
      resources:
        requests:
          cpu: 200m
          memory: 2Gi
        limits:
          memory: 2Gi
      redundancyPolicy: ZeroRedundancy
      #secretName: istio-jaeger-secret
  # volumeMounts: # <5>
  #   - name: certificates
  #     mountPath: /es/certificates/
  #     readOnly: true
  # volumes:
  #   - name: certificates
  #     secret:
  #       secretName: jaeger-istio-certs

  #   options:
  #     es:
  #       server-urls: http://elasticsearch:9200
  #       index-prefix: jaeger
  #       tls:
  #         ca: /es/certificates/ca.crt
  #   secretName: istio-jaeger-secret

  #   esIndexCleaner:
  #     enabled: false                                ## turn the job deployment on and off
  #     numberOfDays: 7                               ## number of days to wait before deleting a record
  #     schedule: "55 23 * * *"                       ## cron expression for it to run
  #     image: jaegertracing/jaeger-es-index-cleaner  ## image of the job

  # volumeMounts: # <5>
  #   - name: certificates
  #     mountPath: /es/certificates/
  #     readOnly: true
  # volumes:
  #   - name: certificates
  #     secret:
  #       secretName: jaeger-istio-certs

