run:
  timeout: 5m

  build-tags:
    - e2e
    - preupgrade
    - postupgrade
    - postdowngrade

  skip-dirs:
    - pkg/client

linters:
  enable:
    - unconvert
    - prealloc
  disable:
    - errcheck
