apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault01.honk.digital:8200"
      path: "kv"
      version: "v2"
      caProvider:
        type: Secret
        name: vault01-ca-bundle
        namespace: external-secrets
        key: vault01.crt
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "3e02ded5-4b89-e20a-71cd-d2dccf9c73e1"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "eso-vault-role"
            key: "secretid"
            namespace: "external-secrets"
