apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-gcp-sa
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-k8s
    kind: ClusterSecretStore
  target:
    name: gcpsm-sa
  data:
    - secretKey: secret-access-credentials
      remoteRef:
        key: /k8s/credentials/gcp_sa
