apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "2"
data:
  extension.config: |-
    extensions:
      - name: metrics
        backend:
          services:
            - url: http://argocd-metrics-server:9003
