apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbor

commonAnnotations:
    reloader.stakater.com/auto: "true"

resources:
  - resources
  - dependencies/cnpg.yaml
  - secrets

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 19.5.5
    releaseName: sentinel
    namespace: harbor
    valuesFile: dependencies/sentinel.yaml

  - name: harbor
    repo: https://helm.goharbor.io
    version: 1.5.0
    releaseName: harbor
    namespace: harbor
    valuesFile: values.yaml

# generatorOptions:
#   disableNameSuffixHash: true

