---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/null0xeth/argo-cd
    path: helm/apps/argo-cd-stack/
    targetRevision: HEAD
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
