---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-operator
  namespace: knative-operator
  labels:
    app.kubernetes.io/version: "1.14.5"
    app.kubernetes.io/name: knative-operator

