apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  annotations:
    # you'll want to change the default over time, e.g. when you move to new storage solution,
    # so we recommend you version them from the outset by suffixing the version
    workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: |
    archiveLogs: true
    s3:
      bucket: argo_workflows
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: argo-minio-creds
        key: accessKey
      secretKeySecret:
        name: argo-minio-creds
        key: secretKey
  my-key: |
    archiveLogs: true
    s3:
      bucket: argo_workflows
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: argo-minio-creds
        key: accessKey
      secretKeySecret:
        name: argo-minio-creds
        key: secretKey
  empty: ""
