apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: The default application project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - namespace: '*'
    server: '*'
    name: in-cluster

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  roles:
  - name: argocd-admin
    description: OIDC elevated permissions
    policies:
    - p, proj:default:argocd-admin, applications, *, default/*, allow
    - p, proj:default:admin, repositories, *, default/*, allow
    groups:
    - argocd-admin
    - argo-admnin

  # A role which provides sync privileges to only the guestbook-dev application, e.g. to provide
  # sync privileges to a CI system
  # - name: ci-role
  #   description: Sync privileges for guestbook-dev
  #   policies:
  #   - p, proj:my-project:ci-role, applications, sync, my-project/guestbook-dev, allow

    # NOTE: JWT tokens can only be generated by the API server and the token is not persisted
    # anywhere by Argo CD. It can be prematurely revoked by removing the entry from this list.
    jwtTokens:
    - iat: 1535390316

  # Sync windows restrict when Applications may be synced. https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/
  # syncWindows:
  # - kind: allow
  #   schedule: '10 1 * * *'
  #   duration: 1h
  #   applications:
  #     - '*-prod'
  #   manualSync: true
  # - kind: deny
  #   schedule: '0 22 * * *'
  #   duration: 1h
  #   namespaces:
  #     - default
  # - kind: allow
  #   schedule: '0 23 * * *'
  #   duration: 1h
  #   clusters:
  #     - in-cluster
  #     - cluster1

  # By default, apps may sync to any cluster specified under the `destinations` field, even if they are not
  # scoped to this project. Set the following field to `true` to restrict apps in this cluster to only clusters
  # scoped to this project.
  permitOnlyProjectScopedClusters: false

  # When using Applications-in-any-namespace, this field determines which namespaces this AppProject permits
  # Applications to reside in. Details: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/
  sourceNamespaces:
  - "*"
