apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

resources:
  - bootstrap/ca-bootstrap-issuer.yaml
  - bootstrap/ca-root-cert.yaml
  - issuers/ca-root-issuer.yaml


