---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-pipelines
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/null0xeth/argo-cd.git
    path: helm/apps/argo-pipelines/
    targetRevision: HEAD
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2


