---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: "1.14"
  controller-custom-certs:
    name: ca-root
    type: Secret
  config:
    defaults:
      container-concurrency: "50"
    autoscaler:
      enable-scale-to-zero: "true"
      scale-to-zero-grace-period: "40s"
      scale-to-zero-pod-retention-period: "42s"
      pod-autoscaler-class: "kpa.autoscaling.knative.dev"
      # Concurrency
      container-concurrency-target-default: "200"
      container-concurrency-target-percentage: "80"
      # Scaling
      min-scale: "0"
      max-scale: "5"
      max-scale-limit: "50"
      initial-scale: "0"
      allow-zero-initial-scale: "true"
      scale-down-delay: "15m"
      stable-window: "40s"
      panic-window-percentage: "20.0"
      panic-threshold-percentage: "150.0"
      max-scale-up-rate: "500.0"
