apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

helmCharts:
    - name: base
      repo: https://istio-release.storage.googleapis.com/charts
      version: 1.23.0-rc.0
      releaseName: istio-base
      namespace: istio-system
      valuesFile: values.yaml

generatorOptions:
    disableNameSuffixHash: true




