apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
spec:
  template:
    spec:
      containers:
      - name: argocd-notifications-controller
        command:
        - argocd-notifications
        - --app-label-selector=!testing
