apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Argo CD's externally facing base URL (optional). Required when configuring SSO
  url: https://argocd.chonk.city

  # Enables application status badge feature
  statusbadge.enabled: "true"

  # Enables anonymous user access. The anonymous users get default role permissions specified argocd-rbac-cm.yaml.
  users.anonymous.enabled: "false"
  extension.config: |-
    extensions:
      - name: metrics
        backend:
          services:
            - url: http://argocd-metrics-server:9003

  # OIDC configuration as an alternative to dex (optional).
  oidc.config: |
    name: Auth0
    issuer: https://honkertown.eu.auth0.com
    clientID: wVjUeq8TFm3NiHBsnRChY7khxVrklTr8
    clientSecret: $argocd-auth0-oidc
    requestedScopes:
    - openid
    - profile
    - email
    - 'https://argocd.chonk.city/claims'
