apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm-params
  labels:
    app.kubernetes.io/name: argocd-cm-params
    app.kubernetes.io/part-of: argocd
data:
  # Argo CD's externally facing base URL (optional). Required when configuring SSO
  url: https://argocd.chonk.city

  # Enables application status badge feature
  statusbadge.enabled: "true"

  # Enables anonymous user access. The anonymous users get default role permissions specified argocd-rbac-cm.yaml.
  users.anonymous.enabled: "false"
  extension.config: |-
    extensions:
      - name: metrics
        backend:
          services:
            - url: http://argocd-metrics-server:9003
