apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-redis-credentials
  labels:
    app.kubernetes.io/name: argocd-redis-credentials
    app.kubernetes.io/part-of: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: argocd-redis  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: argocd-redis-credentials
  - extract:
      key: argocd-redis-credentials
    rewrite:
    - regexp:
        source: "(.*)"
        target: "auth"


