apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-token
  labels:
    app.kubernetes.io/name: argocd-github-token
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: argocd-github-token  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: webhook.github.secret
      remoteRef:
        key: argocd-github-token

