apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-onelogin-oidc
  labels:
    app.kubernetes.io/name: argocd-onelogin-oidc
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: argocd-onelogin-oidc  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: argocd-onelogin-oidc


