apiVersion: apps/v1
kind: Deployment
metadata:
  name: guard-service
  namespace: knative-serving
  labels:
    app: guard-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guard-service
  template:
    metadata:
      labels:
        app: guard-service
    spec:
      serviceAccountName: guard-service-account
      volumes:
        - name: guard-service-tls-volume
          secret:
            secretName: knative-serving-certs
      containers:
        - name: guard-service
          image: gcr.io/knative-releases/knative.dev/security-guard/cmd/guard-service@sha256:0d56ca452200f24bc573f1a17e5cd437a0e7aefc57ce0017ee4c825707cdf7ce
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /secrets
              name: guard-service-tls-volume
          ports:
            - containerPort: 8888
          env:
            - name: GUARD_SERVICE_LABELS
              value: ""
            - name: GUARD_SERVICE_TLS
              value: "false"
            - name: GUARD_SERVICE_AUTH
              value: "false"
            - name: GUARD_SERVICE_LOG_LEVEL
              value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: guard-service
  namespace: knative-serving
spec:
  selector:
    app: guard-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8888

---
