apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.app.driver.name }}
  labels:
    {{ include "cert-manager-csi-driver.labels" . | nindent 4 }}
spec:
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral
{{- if .Values.app.driver.useTokenRequest }}
  tokenRequests:
    - audience: ""
      expirationSeconds: 3600
  requiresRepublish: true
{{- end }}
