{{- if and .Values.metrics.enabled .Values.metrics.podmonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "cert-manager-csi-driver.name" . }}
{{- if .Values.metrics.podmonitor.namespace }}
  namespace: {{ .Values.metrics.podmonitor.namespace }}
{{- else }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
  labels:
    {{- include "cert-manager-csi-driver.labels" . | nindent 4 }}
    prometheus: {{ .Values.metrics.podmonitor.prometheusInstance }}
    {{- with .Values.metrics.podmonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.metrics.podmonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  jobLabel: {{ include "cert-manager-csi-driver.name" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cert-manager-csi-driver.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.metrics.podmonitor.namespace }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
{{- end }}
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: {{ .Values.metrics.podmonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.podmonitor.scrapeTimeout }}
      honorLabels: {{ .Values.metrics.podmonitor.honorLabels }}
      {{- with .Values.metrics.podmonitor.endpointAdditionalProperties }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
{{- end }}
