apiVersion: v1
kind: ServiceAccount
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
metadata:
  labels:
    {{ include "cert-manager-csi-driver.labels" . | nindent 4 }}
  name: {{ include "cert-manager-csi-driver.name" . }}
  namespace: {{ .Release.Namespace | quote }}
