apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

resources:
  - container_health.yaml
  - s3_honker_cloud.yaml
  - honker_dev.yaml

