apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.enable.proxy.extension: "true"
  applicationsetcontroller.enable.progressive.syncs: "true"
  notificationscontroller.selfservice.enabled: "true"
  dexserver.disable.tls: "true"
  server.insecure: "true"

