---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-eventing-operator-aggregated-stable
  labels:
    app.kubernetes.io/version: "1.14.5"
    app.kubernetes.io/name: knative-operator
aggregationRule:
  clusterRoleSelectors:
    # This (along with escalate below) allows the Operator to pick up any
    # roles that are provided to the admin of the cluster by knative eventing
    # automatically.
    - matchExpressions:
        - {key: app.kubernetes.io/name, operator: In, values: ["knative-eventing"]}
rules: [] # Rules are automatically filled in by the controller manager.
