apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

helmCharts:
    - name: zitadel
      repo: https://charts.zitadel.com
      version: 8.5.0
      releaseName: zitadel
      namespace: guardian
      valuesFile: values.yaml

resources:
    - resources/namespace.yaml
    - config/gcp_cluster_store.yaml

generatorOptions:
    disableNameSuffixHash: true



