apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

namespace: traefik

helmCharts:
    - name: traefik
      repo: https://traefik.github.io/charts
      version: 29.0.1
      releaseName: traefik
      namespace: traefik
      valuesFile: values.yaml

resources:
    - resources/middleware
    - resources/routes

generatorOptions:
    disableNameSuffixHash: true
