---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: traefik
  # annotations:
  # labels:
  #   app.kubernetes.io/name: traefik
  #   app.kubernetes.io/instance: traefik-traefik
  #   helm.sh/chart: traefik-23.1.0
  #   app.kubernetes.io/managed-by: Helm
spec:
  headers:
    accessControlAllowMethods: ['GET', 'OPTIONS', 'PUT']
    accessControlMaxAge: 100
    hostsProxyHeaders: ['X-Forwarded-Host']
    stsSeconds: 63072000
    stsIncludeSubdomains: True
    stsPreload: True
    forceSTSHeader: True
    customFrameOptionsValue: allow-from https:chonk.city
    contentTypeNosniff: True
    browserXssFilter: True
    referrerPolicy: same-origin
    permissionsPolicy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()
    customResponseHeaders:
      X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex,
      server: ''
      X-Forwarded-Proto: https
