---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: traefik
  # annotations:
  # labels:
  #   app.kubernetes.io/name: traefik
  #   app.kubernetes.io/instance: traefik-traefik
  #   helm.sh/chart: traefik-23.1.0
  #   app.kubernetes.io/managed-by: Helm
spec:
  rateLimit:
    average: 100
    burst: 50
