apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: metrics-server
  app.kubernetes.io/part-of: metrics-server

resources:
  - apiservice.yaml
  - deployment.yaml
  - rbac.yaml
  - service.yaml
