# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: cert-manager-cf-secret
#   annotations:
#     reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
#     reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
#     reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,cert-manager,external-secrets"
# spec:
#   refreshInterval: 1h # rate SecretManager pulls GCPSM
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: gcpsm # name of the SecretStore (or kind specified)
#   target:
#     name: cert-manager-cf-secret # name of the k8s Secret to be created
#     creationPolicy: Owner
#   dataFrom:
#     - extract:
#         key: cert-manager-cf-secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-cf-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,cert-manager,external-secrets"
spec:
  # Optional, SecretStoreRef defines the default SecretStore to use when fetching the secret data.
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore # or ClusterSecretStore

  # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
  # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h" (from time.ParseDuration)
  # May be set to zero to fetch and create it once
  refreshInterval: "24h"

  # the target describes the secret that shall be created
  # there can only be one target per ExternalSecret
  target:
    name: cert-manager-cf-secret # name of the k8s Secret to be created
    creationPolicy: Owner

    # Specifies what happens to the Secret when data fields are deleted from the provider (e.g., Vault, AWS Parameter Store). Options:
    # - Retain: (default) Retains the Secret if all Secret data fields have been deleted from the provider.
    # - Delete: Removes the Secret if all Secret data fields from the provider are deleted.
    # - Merge: Removes keys from the Secret but not the Secret itself.
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: "k8s/tls/cert-manager-cf-secret"
  #       version: v1
  #       property: key
  #       conversionStrategy: Default
  #       decodingStrategy: Auto
