---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-cf-secret
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm # name of the SecretStore (or kind specified)
  target:
    name: cert-manager-cf-secret # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cert-manager-cf-secret
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: harbor-super-db-secret
# spec:
#   refreshInterval: 1h           # rate SecretManager pulls GCPSM
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: gcpsm                # name of the SecretStore (or kind specified)
#   target:
#     name: harbor-super-db-secret  # name of the k8s Secret to be created
#     creationPolicy: Owner
#     template:
#       type: kubernetes.io/basic-auth
#       data:
#         username: "{{ .username | toString }}"
#         password: "{{ .password | toString }}"
#       metadata:
#         labels:
#           cnpg.io/reload: "true"
#   data:
#   - secretKey: username
#     remoteRef:
#       key: harbor-super-db-secret
#       property: username
#       conversionStrategy: Default
#       decodingStrategy: None
#       metadataPolicy: None
#   - secretKey: password
#     remoteRef:
#       key: harbor-super-db-secret
#       property: password
#       conversionStrategy: Default
#       decodingStrategy: None
#       metadataPolicy: None

# dataFrom:
# - extract:
#     key: harbor-db-secret
#   rewrite:
#   - regexp:
#       source: "(.*)"
#       target: "password"

