apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

helmCharts:
  - name: reloader
    repo: https://stakater.github.io/stakater-charts
    version: 2.1.4
    releaseName: reloader
    namespace: kube-system
    valuesFile: values.yaml

generatorOptions:
  disableNameSuffixHash: true
