apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: prometheus-operator
    app.kubernetes.io/version: 0.75.1
  name: prometheus-operator
  namespace: monitoring
