apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus-operator
    app.kubernetes.io/version: 2.53.0
  name: prometheus-istio-system
  namespace: istio-system
