apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus-operator
    app.kubernetes.io/version: 2.53.0
  name: istio-system
  namespace: istio-system
spec:
  alerting:
    alertmanagers: []
      # - apiVersion: v2
      #   name: alertmanager
      #   namespace: monitoring
      #   port: web
  enableFeatures: []
  externalLabels: {}
  image: quay.io/prometheus/prometheus:v2.53.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: istio-system
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: prometheus-operator
      app.kubernetes.io/version: 2.53.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-istio-system
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: 2.53.0
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: istio-scrape-config.yaml
