apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

resources:
    - 0-service-account.yaml
    - additional-scrape-configs.yaml
    - 1-cluster-role.yaml
    - 2-cluster-role-binding.yaml
    - 3-prometheus.yaml
    - 4-pdb.yaml

generatorOptions:
    disableNameSuffixHash: true




