apiVersion: v2
version: 1.0.0
#name: prometheus
name: metrics-server
dependencies:
  - name: metrics-server
    version: "3.12.*"
    repository: https://kubernetes-sigs.github.io/metrics-server
  # - name: prometheus
  #   version: "25.21.*"
  #   repository: https://prometheus-community.github.io/helm-charts


