apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  reloader.stakater.com/auto: "true"

resources:
  - k8s/cluster_store.yml
  - k8s/vault_approle_secret.yml
  - vault/cluster_store.yaml
  - vault/gcp_sa_secret.yml
  - gcsp/cluster_store.yaml

generatorOptions:
  disableNameSuffixHash: true
