apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-secret-key
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: harbor-secret-key  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: harbor-secret-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-core-secret-key
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                # name of the SecretStore (or kind specified)
  target:
    name: harbor-core-secret-key  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: harbor-secret-key
      rewrite:
        - regexp:
            source: "(.*)"
            target: "secret"

