apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s
spec:
  # Used to select the correct ESO controller (think: ingress.ingressClassName)
  # The ESO controller is instantiated with a specific controller name
  # and filters ES based on this property
  # Optional

  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:
    # (3): Kubernetes provider
    kubernetes:
      server:
        url: "https://k8s.honker.dev:6443"
        caProvider:
          type: Secret
          name: kube-root-ca
          namespace: external-secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
