---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-role-eso
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,cert-manager,external-secrets"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s # name of the SecretStore (or kind specified)
  target:
    name: vault-role-eso # name of the k8s Secret to be created
  data:
    - secretKey: secretid
      remoteRef:
        key: eso-vault-role
        property: secretid
