apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
    - name: cilium
      repo: https://helm.cilium.io/
      version: 1.17.1
      releaseName: cilium
      namespace: kube-system
      valuesFile: values.yaml

# resources:
#     - resources/namespace.yaml
#     - resources/ingress.yaml

# patches:
#     - path: patches/rbac/kubernetesingress.yaml

generatorOptions:
    disableNameSuffixHash: true
