apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

helmCharts:
    - name: jaeger
      repo: https://jaegertracing.github.io/helm-charts
      version: 3.1.1
      releaseName: jaeger
      namespace: observability
      valuesFile: values.yaml

resources:
  - resources/secrets.yaml
generatorOptions:
    disableNameSuffixHash: true





