---
apiVersion: v1
kind: Secret
metadata:
  name: operator-webhook-certs
  namespace: knative-operator
  labels:
    app.kubernetes.io/component: operator-webhook
    app.kubernetes.io/version: "1.14.5"
    app.kubernetes.io/name: knative-operator
# The data is populated at install time.
