apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      bgp_instance: "65000"
  bgpInstances:
    - name: "instance-65000"
      localASN: 65000
      peers:
        - name: "peer-65000-1"
          peerASN: 65000
          peerAddress: "192.168.105.1"
          peerConfigRef:
            name: "cilium-peer"
