# Copyright 2022 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/knative-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard

vars:
  - name: VERSION
    objref:
      kind: ClusterServiceVersion
      name: knative-operator.v$(VERSION)
      apiVersion: operators.coreos.com/v1alpha1
    fieldref:
      fieldpath: spec.version
