crds:
  keep: false

controller:
  # in v3.0+, a second controller can be ran as a hot-standby: https://argo-workflows.readthedocs.io/en/stable/high-availability/#workflow-controller
  replicas: 2 # should be strictly greater than PDB minAvailable
  # enable PDB with at least one Pod
  pdb:
    # -- Configure [Pod Disruption Budget] for the controller pods
    enabled: true
    minAvailable: 1
  serviceMonitor:
    enabled: false
  metricsConfig:
    enabled: true
  telemetryConfig:
    enabled: true

server:
  # enable HPA with at least two Pods
  autoscaling:
    # -- Enable Horizontal Pod Autoscaler ([HPA]) for the Argo Server
    enabled: true
    # -- Minimum number of replicas for the Argo Server [HPA]
    minReplicas: 2 # should be strictly greater than PDB minAvailable
  # enable PDB with at least one Pod
  pdb:
    # -- Configure [Pod Disruption Budget] for the controller pods
    enabled: true
    minAvailable: 1

workflow:
  serviceAccount:
    create: true # Specifies whether a service account should be created
  rbac:
    create: true

useStaticCredentials: true
artifactRepository:
  archiveLogs: false

customArtifactRepository:
  harbor:
    repoUrl: https://harbor.chonk.city/argocd
    usernameSecret:
      name: harbor-creds
      key: username
    passwordSecret:
      name: harbor-creds
      key: password
