apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-operator-webhook-certs
  namespace: monitoring

spec:
  secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""  # Control destination namespaces
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
  dnsNames:
    - prometheus-operator-admission-webhook.default.svc.cluster.local
    - prometheus-operator-admission-webhook.default.svc
  secretName: prometheus-operator-webhook-certs
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
