apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

resources:
    - k8s_resources/namespace.yaml
    - https://github.com/kubernetes-sigs/gateway-api.git/config/crd/
    - components/
    - addons/prometheus/
    - addons/kiali/

generatorOptions:
    disableNameSuffixHash: true

