apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

resources:
    - k8s_resources/namespace.yaml
    - components/
    - addons/kiali/

generatorOptions:
    disableNameSuffixHash: true

