apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

helmCharts:
    - name: descheduler
      repo: https://kubernetes-sigs.github.io/descheduler/
      version: 0.34.0
      releaseName: descheduler
      namespace: kube-system
      valuesFile: values.yaml

generatorOptions:
    disableNameSuffixHash: true



