apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus-adapter
    includeCRDs: true
    repo: https://prometheus-community.github.io/helm-charts
    version: "4.11.0"
    releaseName: prometheus-adapter
    namespace: monitoring
    valuesFile: values.yaml

patches:
  - target:
      kind: APIService
    patch: |
      - op: replace
        path: /apiVersion
        value: apiregistration.k8s.io/v1
