apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    reloader.stakater.com/auto: "true"

helmCharts:
    - name: longhorn
      repo: https://charts.longhorn.io
      version: 1.7.1
      releaseName: longhorn
      namespace: longhorn-system
      valuesFile: values.yaml

resources:
    - resources/namespace.yaml
  #- resources/ingress.yaml

# patches:
#     - path: patches/rbac/kubernetesingress.yaml

generatorOptions:
    disableNameSuffixHash: true

