apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-operator-webhook-certs
  namespace: monitoring
spec:
  dnsNames:
    - prometheus-operator-admission-webhook.default.svc.cluster.local
    - prometheus-operator-admission-webhook.default.svc
  secretName: prometheus-operator-webhook-certs
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
